name: Deploy to AWS EC2 Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
      REPO_URL: https://github.com/SymonMuchemi/ShopSmart

    steps:
      - name: Clone repository
        run: |
          git clone ${{ env.REPO_URL}} || true
      
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build Docker image
        run: |
          cd ~/ShopSmart
          git pull origin main
          sudo docker stop shopsmart || true
          sudo docker rm shopsmart || true
          sudo docker build -t shopsmart .
          sudo docker run -d -p 3000:3000 shopsmart shopsmart
